-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Пацієнт"
(
    "Номер мед. картки" character varying NOT NULL,
    "ПІБ" character varying NOT NULL,
    PRIMARY KEY ("Номер мед. картки")
);

CREATE TABLE IF NOT EXISTS public."Лікар"
(
    "Ліцензія" character varying NOT NULL,
    "ПІБ" character varying NOT NULL,
    "Спеціалізація" character varying NOT NULL,
    PRIMARY KEY ("Ліцензія")
);

CREATE TABLE IF NOT EXISTS public."Запис"
(
    "Ліцензія_лікаря" character varying NOT NULL,
    "Номер_пацієнта" character varying NOT NULL,
    "Дата_запису" timestamp without time zone NOT NULL,
    PRIMARY KEY ("Дата_запису", "Ліцензія_лікаря", "Номер_пацієнта")
);

CREATE TABLE IF NOT EXISTS public."Хвороба"
(
    "Код" character varying NOT NULL,
    "Назва" character varying NOT NULL,
    PRIMARY KEY ("Код")
);

DROP TABLE IF EXISTS public."Діагноз"

CREATE TABLE IF NOT EXISTS public."Діагноз"
(
    "Номер_пацієнта" character varying NOT NULL,
    "Код_хвороби" character varying NOT NULL,
    "Дата_Захворювання" timestamp without time zone NOT NULL,
    PRIMARY KEY ("Номер_пацієнта", "Код_хвороби", "Дата_Захворювання")
);

CREATE TABLE IF NOT EXISTS public."Лікування"
(
    "Ліцензія_лікаря" character varying NOT NULL,
    "Код_хвороби" character varying NOT NULL,
    PRIMARY KEY ("Ліцензія_лікаря", "Код_хвороби")
);

ALTER TABLE IF EXISTS public."Запис"
    ADD FOREIGN KEY ("Номер_пацієнта")
    REFERENCES public."Пацієнт" ("Номер мед. картки") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Запис"
    ADD FOREIGN KEY ("Ліцензія_лікаря")
    REFERENCES public."Лікар" ("Ліцензія") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Діагноз"
    ADD FOREIGN KEY ("Номер_пацієнта")
    REFERENCES public."Пацієнт" ("Номер мед. картки") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Діагноз"
    ADD FOREIGN KEY ("Код_хвороби")
    REFERENCES public."Хвороба" ("Код") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Лікування"
    ADD FOREIGN KEY ("Ліцензія_лікаря")
    REFERENCES public."Лікар" ("Ліцензія") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Лікування"
    ADD FOREIGN KEY ("Код_хвороби")
    REFERENCES public."Хвороба" ("Код") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;